using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Cryptography;
using System.Web;

namespace VendorOpenAPIWebApp
{
    public class CommonCode
    {
        public string GetAppKeySettings(string sKey)
        {
            return ConfigurationManager.AppSettings[sKey].ToString();
        }

        public int Encrypt_Vendor(byte[] data, string MyKey, ref byte[] EncData)
        {
            try
            {
                // Comment for below mention line -- Convert MyKey ie., 64 character Key to Bytes of length : 48
                var _key = Convert.FromBase64String(MyKey);

                // Comment for below mention line -- For more security purpose, again generating Bytes of below mentioned comma seperated values of length : 16
                var _iv = new byte[] { 83, 71, 26, 58, 54, 35, 22, 11, 83, 71, 26, 58, 54, 35, 22, 11 };

                // Comment for below mention line -- Passing both above generated bytes values to below mention Encry System.Security.Cryptography.Rfc2898DeriveBytes function
                var keyBuilder = new Rfc2898DeriveBytes(MyKey, _iv);

                // Comment for below mention line -- String to a filestream, used a memorystream
                var ms = new MemoryStream();

                // Comment for below mention line -- Creating object of System.Security.Cryptography.RijndaelManaged
                var aes = new RijndaelManaged();

                // Comment for below mention line -- Setting Advanced Encryption Standard KeySize
                aes.KeySize = 256;
                //DESCryptoServiceProvider cryptic = new DESCryptoServiceProvider();


                // Comment for below mention line -- A byte array filled with pseudo-random key bytes.
                aes.IV = keyBuilder.GetBytes(Convert.ToInt32(aes.BlockSize / 8));
                aes.Key = keyBuilder.GetBytes(Convert.ToInt32(aes.KeySize / 8));

                // Initializes a new instance of the System.Security.Cryptography.CryptoStream class
                //var cs = new CryptoStream(ms, aes.CreateEncryptor(_key, _iv), CryptoStreamMode.Write);

                var cs = new CryptoStream(ms, aes.CreateEncryptor(), CryptoStreamMode.Write);

                // Comment for below mention line -- Writes a sequence of bytes to the current System.Security.Cryptography.CryptoStream
                cs.Write(data, 0, data.Length);

                // Comment for below mention line -- clears the buffer.
                cs.FlushFinalBlock();

                // The byte array from which this stream was created
                EncData = ms.GetBuffer();
                Array.Resize(ref EncData, (int)(ms.Position - 1L + 1));
                return (int)ms.Position;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        public string GetIPAddress()
        {
            string strHostName = "";
            var strIPAddress = "";
            try
            {
                strHostName = System.Net.Dns.GetHostName();
                IPAddress[] ipaddress = System.Net.Dns.GetHostAddresses(strHostName);
                foreach (IPAddress ip in ipaddress)
                {
                    strIPAddress = ip.ToString();
                }
            }
            catch (Exception ex)
            {
                strIPAddress = "";
            }

            return strIPAddress;
        }

        public class LoginRequestMobileRes
        {
            public ResHeader head = new ResHeader();
            public LoginRequestMobileResBody body = new LoginRequestMobileResBody();
        }

        public class LoginRequestMobileResBody
        {
            public string EmailId { get; set; }
            public string Message { get; set; }
            public int Status { get; set; }
            public string TTManagerId { get; set; }
            public string UserName { get; set; }
            public DateTime ValidUpto { get; set; }
            public string VendorName { get; set; }
        }

        public class ResHeader
        {
            public string responseCode { get; set; }
            public string status { get; set; }
            public string statusDescription { get; set; }
        }
        public class BOCommonReq
        {
            public ReqHeader head = new ReqHeader();
            public BOCommonReqBody body = new BOCommonReqBody();
        }

        public class BOCommonReqBody
        {
            public string ClientCode { get; set; }
            public string FromDate { get; set; }
            public string ToDate { get; set; }
        }

        public class OrderStatusReq
        {
            public ReqHeader head = new ReqHeader();
            public OrderStatusReqBody body = new OrderStatusReqBody();
        }

        public class OrderStatusReqBody
        {
            public string ClientCode { get; set; }
            public List<OrderStatusList> OrdStatusReqList = new List<OrderStatusList>();
        }

        public class OrderStatusList
        {
            public char Exch { get; set; }
            public char ExchType { get; set; }
            public long ScripCode { get; set; }
            public string RemoteOrderID { get; set; }
        }

        public class TradeInformationReq
        {
            public ReqHeader head = new ReqHeader();
            public TradeInformationReqBody body = new TradeInformationReqBody();
        }

        public class TradeInformationReqBody
        {
            public string ClientCode { get; set; }
            public List<TradeInformationList> TradeInformationList = new List<TradeInformationList>();
        }

        public class TradeInformationList
        {
            public char Exch { get; set; }
            public char ExchType { get; set; }
            public long ScripCode { get; set; }
            public string ExchOrderID { get; set; }
        }

        public class PreOrdMarginCalReq
        {
            public ReqHeader head = new ReqHeader();
            public PreOrdMarginCalReqBody body = new PreOrdMarginCalReqBody();
        }

        public class PreOrdMarginCalReqBody
        {
            public string ClientCode { get; set; }
            public string OrderRequestorCode { get; set; }
            public string Exch { get; set; }
            public string ExchType { get; set; }
            public int ScripCode { get; set; }
            public string PlaceModifyCancel { get; set; }
            public string TransactionType { get; set; }
            public string AtMarket { get; set; }
            public double LimitRate { get; set; }
            public string WithSL { get; set; }
            public double SLTriggerRate { get; set; }
            public char IsSLTriggered { get; set; }
            public long Volume { get; set; }
            public long OldTradedQty { get; set; }
            public char ProductType { get; set; }
            public string ExchOrderId { get; set; }
            public string ClientIP { get; set; }
            public int AppSource { get; set; }
        }

        public class CommonReq
        {
            public ReqHeader head = new ReqHeader();
            public CommonBody body = new CommonBody();
        }

        public class CommonBody
        {
            public string ClientCode { get; set; }
        }

        public class LoginRequestReq
        {
            public ReqHeader head = new ReqHeader();
            public LoginRequestReqBody body = new LoginRequestReqBody();
        }

        public class LoginRequestReqBody
        {
            public string ClientCode { get; set; }
            public string Password { get; set; }
            public string LocalIP { get; set; }
            public string PublicIP { get; set; }
            public string HDSerialNumber { get; set; }
            public string MACAddress { get; set; }
            public string MachineID { get; set; }
            public string VersionNo { get; set; }
            public string RequestNo { get; set; }
            public string My2PIN { get; set; }
            public string ConnectionType { get; set; }
        }

        public class LoginRequestMobileReq
        {
            public ReqHeader head = new ReqHeader();
            public LoginRequestMobileReqBody body = new LoginRequestMobileReqBody();
        }

        public class ReqHeader
        {
            public string appName { get; set; }
            public string appVer { get; set; }
            public string key { get; set; }
            public string osName { get; set; }
            public string requestCode { get; set; }
            public string userId { get; set; }
            public string password { get; set; }
        }

        public class LoginRequestMobileReqBody
        {
            public string Email_id { get; set; }
            public string LocalIP { get; set; }
            public string PublicIP { get; set; }
            public string ContactNumber { get; set; }
        }

        public class MarketFeedReq
        {
            public ReqHeader head = new ReqHeader();
            public MarketFeedReqBody body = new MarketFeedReqBody();
        }

        public partial class MarketFeedReqBody
        {
            public string ClientCode { get; set; }
            public int Count { get; set; }
            public List<MarketFeedNew> MarketFeedData = new List<MarketFeedNew>();
            public int ClientLoginType { get; set; }
            public DateTime LastRequestTime { get; set; }
            public string RefreshRate { get; set; }
        }

        public class MarketFeedNew
        {
            public string Exch { get; set; }
            public string ExchType { get; set; }
            public string ScripCode { get; set; }
        }

        public partial class ReqPlaceSMOOrderDetails
        {
            public ReqPlaceSMOOrder _ReqData = new ReqPlaceSMOOrder();
            public int AppSource;
        }

        public partial class ReqPlaceSMOOrder
        {
            public ReqHeader head = new ReqHeader();
            public ReqPlaceSMOOrderMain body = new ReqPlaceSMOOrderMain();
        }

        public partial class ReqPlaceSMOOrderMain
        {
            public string ClientCode { get; set; }
            public string OrderRequesterCode { get; set; }
            public char RequestType { get; set; }
            public string BuySell { get; set; }
            public long Qty { get; set; }
            public string Exch { get; set; }
            public string ExchType { get; set; }
            public long DisQty { get; set; }
            public bool AtMarket { get; set; }
            public long ExchOrderID { get; set; }
            public double LimitPriceInitialOrder { get; set; }
            public double TriggerPriceInitialOrder { get; set; }
            public double LimitPriceProfitOrder { get; set; }
            public double LimitPriceForSL { get; set; }
            public double TriggerPriceForSL { get; set; }
            public double TrailingSL { get; set; }
            public Boolean StopLoss { get; set; }
            public int ScripCode { get; set; }
            public string OrderFor { get; set; }
            public string UniqueOrderIDNormal { get; set; }
            public string UniqueOrderIDSL { get; set; }
            public string UniqueOrderIDLimit { get; set; }
            public long LocalOrderIDNormal { get; set; }
            public long LocalOrderIDSL { get; set; }
            public long LocalOrderIDLimit { get; set; }
            public string PublicIP { get; set; }
        }

        public partial class ReqAdvModifySMOOrderDetails
        {
            public ReqAdvModifySMOOrder _ReqData = new ReqAdvModifySMOOrder();
            public int AppSource;
        }

        public partial class ReqAdvModifySMOOrder
        {
            public ReqHeader head = new ReqHeader();
            public ReqAdvanceModifySMOOrderMain body = new ReqAdvanceModifySMOOrderMain();
        }

        public partial class ReqAdvanceModifySMOOrderMain
        {
            public string ClientCode { get; set; }
            public string OrderRequesterCode { get; set; }
            public string OrderFor { get; set; }
            public char Exchange { get; set; }
            public char ExchangeType { get; set; }
            public double Price { get; set; }
            public long OrderID { get; set; }
            public string OrderType { get; set; }
            public long Qty { get; set; }
            public DateTime OrderDateTime { get; set; }
            public long ScripCode { get; set; }
            public bool AtMarket { get; set; }
            public string RemoteOrderID { get; set; }
            public string ExchOrderID { get; set; }
            public long DisQty { get; set; }
            public double StopLossPrice { get; set; }
            public bool IsStopLossOrder { get; set; }
            public bool IOCOrder { get; set; }
            public bool IsIntraday { get; set; }
            public DateTime ValidTillDate { get; set; }
            public char AHPlaced { get; set; }
            public string PublicIP { get; set; }
            public OrderValidity iOrderValidity { get; set; }
            public double TrailingSL { get; set; }
            public int LegType { get; set; }
            public int TMOPartnerOrderID { get; set; }
        }

        public partial class ReqOrderRequest
        {
            public ReqOrderRequestMain _ReqData = new ReqOrderRequestMain();
            public int AppSource;
        }
        public partial class ReqOrderRequestMain
        {
            public ReqHeader head = new ReqHeader();
            public ReqOrderRequestBody body = new ReqOrderRequestBody();
        }

        public partial class ReqOrderRequestBody
        {
            public string ClientCode { get; set; }
            public string OrderFor { get; set; }
            public char Exchange { get; set; }
            public char ExchangeType { get; set; }
            public double Price { get; set; }
            public long OrderID { get; set; }
            public string OrderType { get; set; }
            public long Qty { get; set; }
            public DateTime OrderDateTime { get; set; }
            public long ScripCode { get; set; }
            public bool AtMarket { get; set; }
            public string RemoteOrderID { get; set; }
            public string ExchOrderID { get; set; }
            public long DisQty { get; set; }
            public double StopLossPrice { get; set; }
            public bool IsStopLossOrder { get; set; }
            public bool IOCOrder { get; set; }
            public bool IsIntraday { get; set; }
            public DateTime ValidTillDate { get; set; }
            public char AHPlaced { get; set; }
            public string PublicIP { get; set; }
            public OrderValidity iOrderValidity { get; set; }
            public long TradedQty { get; set; }
            public string OrderRequesterCode { get; set; }
        }

        public enum OrderValidity : short
        {
            Day = 0,
            GTD = 1,
            GTC = 2,
            IOC = 3,
            EOS = 4,
            VTD = 5,
            FOK = 6
        }
    }
}