Imports System.IO
Imports System.Net
Imports System.Security.Cryptography

Public Class CommonCode
    Public Function GetAppKeySettings(ByVal sKey As String) As String
        Return ConfigurationManager.AppSettings(sKey).ToString()
    End Function

    Public Shared Function Encrypt_Vendor(ByVal data() As Byte, ByVal MyKey As String, ByRef EncData() As Byte) As Int32
        Try
            'Comment for below mention line -- Convert MyKey ie., 64 character Key to Bytes of length : 48
            Dim _key() As Byte = Convert.FromBase64String(MyKey)

            'Comment for below mention line -- For more security purpose, again generating Bytes of below mentioned comma seperated values of length : 16
            Dim _iv() As Byte = {83, 71, 26, 58, 54, 35, 22, 11, 83, 71, 26, 58, 54, 35, 22, 11}

            'Comment for below mention line -- Passing both above generated bytes values to below mention Encry System.Security.Cryptography.Rfc2898DeriveBytes function
            Dim keyBuilder As Rfc2898DeriveBytes = New Rfc2898DeriveBytes(MyKey, _iv)

            'Comment for below mention line -- String to a filestream, used a memorystream
            Dim ms As New MemoryStream()

            'Comment for below mention line -- Creating object of System.Security.Cryptography.RijndaelManaged
            Dim aes As New RijndaelManaged()

            'Comment for below mention line -- Setting Advanced Encryption Standard KeySize
            aes.KeySize = 256

            'Comment for below mention line -- A byte array filled with pseudo-random key bytes.
            aes.IV = keyBuilder.GetBytes(CType(aes.BlockSize / 8, Integer))
            aes.Key = keyBuilder.GetBytes(CType(aes.KeySize / 8, Integer))

            'Initializes a new instance of the System.Security.Cryptography.CryptoStream class
            Dim cs As New CryptoStream(ms, aes.CreateEncryptor, CryptoStreamMode.Write)

            'Comment for below mention line -- Writes a sequence of bytes to the current System.Security.Cryptography.CryptoStream
            cs.Write(data, 0, data.Length)

            'Comment for below mention line -- clears the buffer.
            cs.FlushFinalBlock()

            'The byte array from which this stream was created
            EncData = ms.GetBuffer()
            ReDim Preserve EncData(ms.Position - 1)
            Return ms.Position
        Catch ex As Exception
            Throw ex
        End Try
    End Function

    Public Function GetIPAddress() As String
        Dim strHostName As String = ""
        Dim strIPAddress = ""

        Try
            strHostName = Net.Dns.GetHostName()
            Dim ipaddress As IPAddress() = Net.Dns.GetHostAddresses(strHostName)

            For Each ip As IPAddress In ipaddress
                strIPAddress = ip.ToString()
            Next

        Catch ex As Exception
            strIPAddress = ""
        End Try

        Return strIPAddress
    End Function



    Public Class LoginRequestMobileRes
        Public head As ResHeader = New ResHeader()
        Public body As LoginRequestMobileResBody = New LoginRequestMobileResBody()
    End Class

    Public Class LoginRequestMobileResBody
        Public Property EmailId As String
        Public Property Message As String
        Public Property Status As Integer
        Public Property TTManagerId As String
        Public Property UserName As String
        Public Property ValidUpto As Date
        Public Property VendorName As String
    End Class

    Public Class ResHeader
        Public Property responseCode As String
        Public Property status As String
        Public Property statusDescription As String
    End Class

    Public Class BOCommonReq
        Public head As ReqHeader = New ReqHeader()
        Public body As BOCommonReqBody = New BOCommonReqBody()
    End Class

    Public Class BOCommonReqBody
        Public Property ClientCode As String
        Public Property FromDate As String
        Public Property ToDate As String
    End Class

    Public Class OrderStatusReq
        Public head As ReqHeader = New ReqHeader()
        Public body As OrderStatusReqBody = New OrderStatusReqBody()
    End Class

    Public Class OrderStatusReqBody
        Public Property ClientCode As String
        Public OrdStatusReqList As List(Of OrderStatusList) = New List(Of OrderStatusList)()
    End Class

    Public Class OrderStatusList
        Public Property Exch As Char
        Public Property ExchType As Char
        Public Property ScripCode As Long
        Public Property RemoteOrderID As String
    End Class

    Public Class TradeInformationReq
        Public head As ReqHeader = New ReqHeader()
        Public body As TradeInformationReqBody = New TradeInformationReqBody()
    End Class

    Public Class TradeInformationReqBody
        Public Property ClientCode As String
        Public TradeInformationList As List(Of TradeInformationList) = New List(Of TradeInformationList)()
    End Class

    Public Class TradeInformationList
        Public Property Exch As Char
        Public Property ExchType As Char
        Public Property ScripCode As Long
        Public Property ExchOrderID As String
    End Class

    Public Class PreOrdMarginCalReq
        Public head As ReqHeader = New ReqHeader()
        Public body As PreOrdMarginCalReqBody = New PreOrdMarginCalReqBody()
    End Class

    Public Class PreOrdMarginCalReqBody
        Public Property ClientCode As String
        Public Property OrderRequestorCode As String
        Public Property Exch As String
        Public Property ExchType As String
        Public Property ScripCode As Integer
        Public Property PlaceModifyCancel As String
        Public Property TransactionType As String
        Public Property AtMarket As String
        Public Property LimitRate As Double
        Public Property WithSL As String
        Public Property SLTriggerRate As Double
        Public Property IsSLTriggered As Char
        Public Property Volume As Long
        Public Property OldTradedQty As Long
        Public Property ProductType As Char
        Public Property ExchOrderId As String
        Public Property ClientIP As String
        Public Property AppSource As Integer
    End Class

    Public Class CommonReq
        Public head As ReqHeader = New ReqHeader()
        Public body As CommonBody = New CommonBody()
    End Class

    Public Class CommonBody
        Public Property ClientCode As String
    End Class

    Public Class LoginRequestReq
        Public head As ReqHeader = New ReqHeader()
        Public body As LoginRequestReqBody = New LoginRequestReqBody()
    End Class

    Public Class LoginRequestReqBody
        Public Property ClientCode As String
        Public Property Password As String
        Public Property LocalIP As String
        Public Property PublicIP As String
        Public Property HDSerialNumber As String
        Public Property MACAddress As String
        Public Property MachineID As String
        Public Property VersionNo As String
        Public Property RequestNo As String
        Public Property My2PIN As String
        Public Property ConnectionType As String
    End Class

    Public Class FetchSVDetailsReq
        Public head As ReqHeader = New ReqHeader()
        Public body As New FetchSVDetailsReqBody
    End Class

    Public Class FetchSVDetailsReqBody
        Public Clientid As String
    End Class

    Public Class MarketFeedReq
        Public head As ReqHeader = New ReqHeader()
        Public body As MarketFeedReqBody = New MarketFeedReqBody()
    End Class

    Public Class MarketFeedReqBody
        Public Property ClientCode As String
        Public Property Count As Integer
        Public MarketFeedData As List(Of MarketFeedNew) = New List(Of MarketFeedNew)()
        Public Property ClientLoginType As Integer
        Public Property LastRequestTime As Date
        Public Property RefreshRate As String
    End Class

    Public Class MarketFeedNew
        Public Property Exch As String
        Public Property ExchType As String
        Public Property ScripCode As String
    End Class

    Partial Public Class ReqAdvModifySMOOrderDetails
        Public _ReqData As ReqAdvModifySMOOrder = New ReqAdvModifySMOOrder()
        Public AppSource As Integer
    End Class

    Partial Public Class ReqAdvModifySMOOrder
        Public head As ReqHeader = New ReqHeader()
        Public body As ReqAdvanceModifySMOOrderMain = New ReqAdvanceModifySMOOrderMain()
    End Class

    Partial Public Class ReqAdvanceModifySMOOrderMain
        Public Property ClientCode As String
        Public Property OrderRequesterCode As String
        Public Property OrderFor As String
        Public Property Exchange As Char
        Public Property ExchangeType As Char
        Public Property Price As Double
        Public Property OrderID As Long
        Public Property OrderType As String
        Public Property Qty As Long
        Public Property OrderDateTime As Date
        Public Property ScripCode As Long
        Public Property AtMarket As Boolean
        Public Property RemoteOrderID As String
        Public Property ExchOrderID As String
        Public Property DisQty As Long
        Public Property StopLossPrice As Double
        Public Property IsStopLossOrder As Boolean
        Public Property IOCOrder As Boolean
        Public Property IsIntraday As Boolean
        Public Property ValidTillDate As Date
        Public Property AHPlaced As Char
        Public Property PublicIP As String
        Public Property iOrderValidity As OrderValidity
        Public Property TrailingSL As Double
        Public Property LegType As Integer
        Public Property TMOPartnerOrderID As Integer
    End Class

    Partial Public Class ReqPlaceSMOOrderDetails
        Public _ReqData As ReqPlaceSMOOrder = New ReqPlaceSMOOrder()
        Public AppSource As Integer
    End Class

    Partial Public Class ReqPlaceSMOOrder
        Public head As ReqHeader = New ReqHeader()
        Public body As ReqPlaceSMOOrderMain = New ReqPlaceSMOOrderMain()
    End Class

    Partial Public Class ReqPlaceSMOOrderMain
        Public Property ClientCode As String
        Public Property OrderRequesterCode As String
        Public Property RequestType As Char
        Public Property BuySell As String
        Public Property Qty As Long
        Public Property Exch As String
        Public Property ExchType As String
        Public Property DisQty As Long
        Public Property AtMarket As Boolean
        Public Property ExchOrderID As Long
        Public Property LimitPriceInitialOrder As Double
        Public Property TriggerPriceInitialOrder As Double
        Public Property LimitPriceProfitOrder As Double
        Public Property LimitPriceForSL As Double
        Public Property TriggerPriceForSL As Double
        Public Property TrailingSL As Double
        Public Property StopLoss As Boolean
        Public Property ScripCode As Integer
        Public Property OrderFor As String
        Public Property UniqueOrderIDNormal As String
        Public Property UniqueOrderIDSL As String
        Public Property UniqueOrderIDLimit As String
        Public Property LocalOrderIDNormal As Long
        Public Property LocalOrderIDSL As Long
        Public Property LocalOrderIDLimit As Long
        Public Property PublicIP As String
    End Class

    Public Class ReqOrderRequest
        Public _ReqData As ReqOrderRequestMain = New ReqOrderRequestMain()
        Public AppSource As Integer
    End Class

    Public Class ReqOrderRequestMain
        Public head As ReqHeader = New ReqHeader()
        Public body As ReqOrderRequestBody = New ReqOrderRequestBody()
    End Class
    Public Class ReqOrderRequestBody
        Public Property ClientCode As String
        Public Property OrderFor As String
        Public Property Exchange As Char
        Public Property ExchangeType As Char
        Public Property Price As Double
        Public Property OrderID As Long
        Public Property OrderType As String
        Public Property Qty As Long
        Public Property OrderDateTime As DateTime
        Public Property ScripCode As Long
        Public Property AtMarket As Boolean
        Public Property RemoteOrderID As String
        Public Property ExchOrderID As String
        Public Property DisQty As Long
        Public Property StopLossPrice As Double
        Public Property IsStopLossOrder As Boolean
        Public Property IOCOrder As Boolean
        Public Property IsIntraday As Boolean
        Public Property ValidTillDate As DateTime
        Public Property AHPlaced As Char
        Public Property PublicIP As String
        Public Property iOrderValidity As OrderValidity
        Public Property TradedQty As Long
        Public Property OrderRequesterCode As String
    End Class

    Public Enum OrderValidity As Int16
        Day = 0
        GTD = 1
        GTC = 2
        IOC = 3
        EOS = 4
        VTD = 5
        FOK = 6
    End Enum

    Public Class LoginRequestMobileReq
        Public head As ReqHeader = New ReqHeader()
        Public body As LoginRequestMobileReqBody = New LoginRequestMobileReqBody()
    End Class

    Public Class ReqHeader
        Public Property appName As String
        Public Property appVer As String
        Public Property key As String
        Public Property osName As String
        Public Property requestCode As String
        Public Property userId As String
        Public Property password As String
    End Class

    Public Class LoginRequestMobileReqBody
        Public Property Email_id As String
        Public Property LocalIP As String
        Public Property PublicIP As String
        Public Property ContactNumber As String
    End Class


End Class
